# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Larapaper
version: "0.31.0"
slug: larapaper
description: BYOS for TRMNL
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - amd64
ports:
  8080/tcp: 2300
init: false
image: "ghcr.io/usetrmnl/larapaper"
webui: http://[HOST]:[PORT:2300]/
panel_icon: mdi:mdiChartBoxOutline
# Deactivate AppArmor for Testing
apparmor: false
environment:
  DB_DATABASE: /data/storage/database.sqlite